const leaderboardData = [
  { image: "/LogoHMPS/HIMABIO.png", himpunan: "HIMABIO \"Nymphaea\" ITB", gold: 1, silver: 1, bronze: 0, score: 8 },
  { image: "/LogoHMPS/HIMA_TG.png", himpunan: "HIMA TG \"TERRA\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HIMAFI.png", himpunan: "HIMAFI ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HIMAMIKRO.png", himpunan: "HIMAMIKRO \"Archaea\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HIMAREKTA.png", himpunan: "HIMAREKTA \"Agrapana\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HIMASDA.png", himpunan: "Himasda-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HIMASTRON.png", himpunan: "Himastron ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HIMATEK.png", himpunan: "HIMATEK-ITB", gold: 0, silver: 0, bronze: 1, score: 1 },
  { image: "/LogoHMPS/HIMATIKA.png", himpunan: "HIMATIKA ITB", gold: 1, silver: 0, bronze: 0, score: 5 },
  { image: "/LogoHMPS/HME.png", himpunan: "HME ITB", gold: 1, silver: 1, bronze: 0, score: 8 },
  { image: "/LogoHMPS/HMF.png", himpunan: "HMF \'Ars Praeparandi\' ITB", gold: 0, silver: 1, bronze: 0, score: 3 },
  { image: "/LogoHMPS/HMFT.png", himpunan: "HMFT-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HMH.png", himpunan: "HMH 'Selva' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HMIF.png", himpunan: "HMIF ITB", gold: 1, silver: 0, bronze: 2, score: 7 },
  { image: "/LogoHMPS/HMK.png", himpunan: "HMK 'AMISCA' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HMM.png", himpunan: "HMM ITB", gold: 0, silver: 1, bronze: 2, score: 5 },
  { image: "/LogoHMPS/HMME.png", himpunan: "HMME \"Atmosphaira\" ITB", gold: 0, silver: 0, bronze: 1, score: 1 },
  { image: "/LogoHMPS/HMO.png", himpunan: "HMO \"TRITON\" ITB", gold: 1, silver: 2, bronze: 1, score: 12 },
  { image: "/LogoHMPS/HMP.png", himpunan: "HMP PL ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HMPG.png", himpunan: "HMPG ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HMPP.png", himpunan: "HMPP 'Vadra' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HMRH.png", himpunan: "HMRH ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HMS.png", himpunan: "HMS ITB", gold: 1, silver: 0, bronze: 1, score: 6 },
  { image: "/LogoHMPS/HMT.png", himpunan: "HMT-ITB", gold: 3, silver: 0, bronze: 0, score: 15 },
  { image: "/LogoHMPS/HMTB.png", himpunan: "HMTB 'RINUVA' ITB", gold: 0, silver: 0, bronze: 1, score: 1 },
  { image: "/LogoHMPS/HMTG.png", himpunan: "HMTG \"GEA\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/HMTL.png", himpunan: "HMTL ITB", gold: 0, silver: 1, bronze: 0, score: 3 },
  { image: "/LogoHMPS/HMTM.png", himpunan: "HMTM \"PATRA\" ITB", gold: 0, silver: 1, bronze: 0, score: 3 },
  { image: "/LogoHMPS/IMA_G.png", himpunan: "IMA-G ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/IMG.png", himpunan: "IMG-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/IMK.png", himpunan: "IMK \"ARTHA\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/IMMG.png", himpunan: "IMMG ITB", gold: 1, silver: 1, bronze: 1, score: 9 },
  { image: "/LogoHMPS/IMT.png", himpunan: "IMT \"Signum\" ITB", gold: 0, silver: 1, bronze: 0, score: 3 },
  { image: "/LogoHMPS/KMIL.png", himpunan: "KMIL ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/KMKL.png", himpunan: "KMKL-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/KMM.png", himpunan: "KMM ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/KMPN.png", himpunan: "KMPN", gold: 0, silver: 1, bronze: 0, score: 3 },
  { image: "/LogoHMPS/KMSR.png", himpunan: "KMSR ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/LogoHMPS/MTI.png", himpunan: "MTI ITB", gold: 1, silver: 0, bronze: 0, score: 5 },
  { image: "/LogoHMPS/MTM.png", himpunan: "MTM ITB", gold: 0, silver: 0, bronze: 1, score: 1 },
];

export default leaderboardData;