const leaderboardData = [
  { image: "/DATABASE HIMPUNAN/HIMABIO _Nymphaea_ ITB.jfif", himpunan: "HIMABIO \"Nymphaea\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HIMA TG _TERRA_ ITB.jpg", himpunan: "HIMA TG \"TERRA\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HIMAFI ITB.jpg", himpunan: "HIMAFI ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HIMAMIKRO _Archaea_ ITB.png", himpunan: "HIMAMIKRO \"Archaea\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HIMAREKTA _Agrapana_ ITB.png", himpunan: "HIMAREKTA \"Agrapana\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/Himasda-ITB.png", himpunan: "Himasda-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/Himastron ITB.jfif", himpunan: "Himastron ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HIMATEK-ITB.png", himpunan: "HIMATEK-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HIMATIKA ITB.png", himpunan: "HIMATIKA ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HME ITB.png", himpunan: "HME ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMF _Ars Praeparandi_ ITB.png", himpunan: "HMF \'Ars Praeparandi\' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMFT-ITB.png", himpunan: "HMFT-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMH _Selva_ ITB.png", himpunan: "HMH 'Selva' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMIF ITB.jpg", himpunan: "HMIF ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMK _AMISCA_ ITB.png", himpunan: "HMK 'AMISCA' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMM ITB.jfif", himpunan: "HMM ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMME _Atmosphaira_ ITB.png", himpunan: "HMME \"Atmosphaira\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMO _TRITON_ ITB.png", himpunan: "HMO \"TRITON\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMP PL ITB.png", himpunan: "HMP PL ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMPG ITB.png", himpunan: "HMPG ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMPP _Vadra_ ITB.png", himpunan: "HMPP 'Vadra' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMRH ITB.png", himpunan: "HMRH ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMS ITB.png", himpunan: "HMS ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMT-ITB.jpg", himpunan: "HMT-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMTB _RINUVA_ ITB.png", himpunan: "HMTB 'RINUVA' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMTG _GEA_ ITB.jpg", himpunan: "HMTG \"GEA\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMTL ITB.jpg", himpunan: "HMTL ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/HMTM _PATRA_ ITB.png", himpunan: "HMTM \"PATRA\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/IMA-G ITB.png", himpunan: "IMA-G ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/IMG-ITB.jpg", himpunan: "IMG-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/IMK _ARTHA_ ITB.jfif", himpunan: "IMK \"ARTHA\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/IMMG ITB.png", himpunan: "IMMG ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/IMT _Signum_ ITB.jpg", himpunan: "IMT \"Signum\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/KMIL ITB.jpg", himpunan: "KMIL ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/KMKL-ITB.png", himpunan: "KMKL-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/KMM ITB.png", himpunan: "KMM ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/KMPN.png", himpunan: "KMPN ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/KMSR ITB.jfif", himpunan: "KMSR ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/MTI ITB.png", himpunan: "MTI ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/DATABASE HIMPUNAN/MTM ITB.png", himpunan: "MTM ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
];

export default leaderboardData;