const leaderboardData = [
  { image: "/HIMABIO.png", himpunan: "HIMABIO \"Nymphaea\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HIMA_TG.jpg", himpunan: "HIMA TG \"TERRA\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HIMAFI.jpg", himpunan: "HIMAFI ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HIMAMIKRO.png", himpunan: "HIMAMIKRO \"Archaea\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HIMAREKTA.png", himpunan: "HIMAREKTA \"Agrapana\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HIMASDA.png", himpunan: "Himasda-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HIMASTRON.png", himpunan: "Himastron ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HIMATEK.png", himpunan: "HIMATEK-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HIMATIKA.png", himpunan: "HIMATIKA ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HME.png", himpunan: "HME ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMF.png", himpunan: "HMF \'Ars Praeparandi\' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMFT.png", himpunan: "HMFT-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMH.png", himpunan: "HMH 'Selva' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMIF.jpg", himpunan: "HMIF ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMK.png", himpunan: "HMK 'AMISCA' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMM.png", himpunan: "HMM ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMME.png", himpunan: "HMME \"Atmosphaira\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMO.png", himpunan: "HMO \"TRITON\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMP.png", himpunan: "HMP PL ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMPG.png", himpunan: "HMPG ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMPP.png", himpunan: "HMPP 'Vadra' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMRH.png", himpunan: "HMRH ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMS.png", himpunan: "HMS ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMT.jpg", himpunan: "HMT-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMTB.png", himpunan: "HMTB 'RINUVA' ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMTG.jpg", himpunan: "HMTG \"GEA\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMTL.jpg", himpunan: "HMTL ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/HMTM.png", himpunan: "HMTM \"PATRA\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/IMA_G.png", himpunan: "IMA-G ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/IMG.jpg", himpunan: "IMG-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/IMK.png", himpunan: "IMK \"ARTHA\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/IMMG.png", himpunan: "IMMG ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/IMT.jpg", himpunan: "IMT \"Signum\" ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/KMIL.jpg", himpunan: "KMIL ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/KMKL.png", himpunan: "KMKL-ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/KMM.png", himpunan: "KMM ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/KMPN.png", himpunan: "KMPN ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/KMSR.png", himpunan: "KMSR ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/MTI.png", himpunan: "MTI ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
  { image: "/MTM.png", himpunan: "MTM ITB", gold: 0, silver: 0, bronze: 0, score: 0 },
];

export default leaderboardData;