export const schedule = [
    {
        week : 1,
        match :
        [{
            day       : 1,
            tanggal   : "Jumat, 1 November 2024",
            lokasi    : "Online",
            sportName : "Mobile Legends: Bang Bang",
            waktu     : "19:00",
            tim1      : "Himpunan Mahasiswa Fisika Teknik (A)",
            image1    : "/HMFT.png",
            skor1     : "0",
            tim2      : "Himpunan Mahasiswa Elektroteknik",
            image2    : "/HME.png",
            skor2     : "0",
        },
        {
            day       : 1,
            tanggal   : "Jumat, 1 November 2024",
            lokasi    : "Online",
            sportName : "Mobile Legends: Bang Bang",
            waktu     : "19:00",
            tim1      : "Ikatan Mahasiswa Kewirausahaan \"Artha\"",
            image1    : "/IMK.png",
            skor1     : "0",
            tim2      : "Keluarga Mahasiswa Manajemen",
            image2    : "/KMM.png",
            skor2     : "0",
        },
        {
            day       : 1,
            tanggal   : "Jumat, 1 November 2024",
            lokasi    : "Online",
            sportName : "Mobile Legends: Bang Bang",
            waktu     : "19:00",
            tim1      : "Himpunan Mahasiswa Elektronik",
            image1    : "/HME.png",
            skor1     : "0",
            tim2      : "Himpunan Mahasiswa Biologi \"Nymphaea\"",
            image2    : "/HIMABIO.png",
            skor2     : "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Fisika Teknik (A)",
            image1 : "/HMFT.png",
            skor1: "0",
            tim2: "Ikatan Mahasiswa Metalurgi (B)",
            image2 : "/IMMG.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Ikatan Mahasiswa Kewirausahaan \"Artha\"",
            image1 : "/IMK.png",
            skor1: "0",
            tim2: "Keluarga Mahasiswa Manajemen (B)",
            image2 : "/KMM.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Elektroteknik (B)",
            image1 : "/HME.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Biologi \"Nymphaea\"",
            image2 : "/HIMABIO.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Tambang (A)",
            image1 : "/HMT.jpg",
            skor1: "0",
            tim2: "Keluarga Mahasiswa Penerbangan (A)",
            image2 : "/KMPN.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Ikatan Mahasiswa Telekomunikasi \"Signum\" (A)",
            image1 : "/IMT.jpg",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Perencanaan Wilayah dan Kota (A)",
            image2 : "/HMP.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Fisika Teknik (B)",
            image1 : "/HMFT.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Informatika (A)",
            image2 : "/HMIF.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Astronomi (B)",
            image1 : "/HIMASTRON.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Teknik Kimia (B)",
            image2 : "/HIMATEK.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Farmasi 'AP' (A)",
            image1 : "/HMF.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Teknik Geofisika 'TERRA' (B)",
            image2 : "/HIMA_TG.jpg",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Sipil (B)",
            image1 : "/HMS.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Oseanografi 'TRITON' (A)",
            image2 : "/HMO.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Ikatan Mahasiswa Geodesi (A)",
            image1 : "/IMG.jpg",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Matematika (A)",
            image2 : "/HIMATIKA.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Meteorologi 'Atmosphaira' (B)",
            image1 : "/HMME.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Teknik Geologi 'GEA' (B)",
            image2 : "/HMTG.jpg",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Perencanaan Wilayah dan Kota (B)",
            image1 : "/HMP.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Teknik Geofisika 'TERRA' (A)",
            image2 : "/HIMA_TG.jpg",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Ikatan Mahasiswa Arsitektur-Gunadharma (B)",
            image1 : "/IMA_G.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Perencanaan Wilayah dan Kota Komisariat",
            image2 : "/HMP_Kom.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Teknik Lingkungan (A)",
            image1 : "/HMTL.jpg",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Matematika (B)",
            image2 : "/HIMATIKA.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Ikatan Mahasiswa Arsitektur-Gunadharma (A)",
            image1 : "/IMA_G.png",
            skor1: "0",
            tim2: "Keluarga Mahasiswa Teknik Kelautan (B)",
            image2 : "/KMKL.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Mahasiswa Teknik Industri (A)",
            image1 : "/MTI.png",
            skor1: "0",
            tim2: "Keluarga Mahasiswa Manajemen (A)",
            image2 : "/KMM.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Oseanografi \"TRITON\" (B)",
            image1 : "/HMO.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Meteorologi (A)",
            image2 : "/HMM.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Rekayasa Hayati",
            image1 : "/HMRH.png",
            skor1: "0",
            tim2: "Keluarga Mahasiswa Seni Rupa",
            image2 : "/KMSR.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Teknik Kimia (A)",
            image1 : "/HIMATEK.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Informatika (B)",
            image2 : "/HMIF.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Elektroteknik (A)",
            image1 : "/HME.png",
            skor1: "0",
            tim2: "Keluarga Mahasiswa Penerbangan (B)",
            image2 : "/KMPN.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Mikrobiologi \"Archaea\"",
            image1 : "/HIMAMIKRO.png",
            skor1: "0",
            tim2: "Ikatan Mahasiswa Telekomunikasi \"Signum\" (B)",
            image2 : "/IMT.jpg",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Teknik Material (B)",
            image1 : "/MTM.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Teknik Geologi \"GEA\" (A)",
            image2 : "/HMTG.jpg",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Mikrobiologi \"Archaea\" (B)",
            image1 : "/HIMAMIKRO.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Teknik Lingkungan (B)",
            image2 : "/HMTL.jpg",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Meteorologi (B)",
            image1 : "/HMM.png",
            skor1: "0",
            tim2: "Ikatan Mahasiswa Metalurgi (A)",
            image2 : "/IMMG.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Mahasiswa Teknik Industri (B)",
            image1 : "/MTI.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Kimia \"AMISCA\"",
            image2 : "/AMISCA.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Sipil (A)",
            image1 : "/HMS.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Farmasi 'AP' (B)",
            image2 : "/HMF.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Teknik Perminyakan \"PATRA\"",
            image1 : "/HMTM.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Fisika (A)",
            image2 : "/HIMAFI.jpg",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Keluarga Mahasiswa Teknik Kelautan (A)",
            image1 : "/KMKL.png",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Astronomi (A)",
            image2 : "/HIMASTRON.png",
            skor2: "0",
        },
        {
            day: 1,
            tanggal: "Jumat, 1 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "19:00",
            tim1: "Himpunan Mahasiswa Tambang (B)",
            image1 : "/HMT.jpg",
            skor1: "0",
            tim2: "Himpunan Mahasiswa Teknik Material (A)",
            image2 : "/MTM.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "Himpunan Mahasiswa Fisika (B)",
            image1 : "/HIMAFI.jpg",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "Himpunan Mahasiswa Meteorologi \"Atmosphaira\" (A)",
            image1 : "/HMME.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "Ikatan Mahasiswa Geodesi (B)",
            image1 : "/IMG.jpg",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 2,
            tanggal: "Sabtu, 2 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 3,
            tanggal: "Minggu, 3 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "13:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 3,
            tanggal: "Minggu, 3 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "13:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 3,
            tanggal: "Minggu, 3 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "13:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 3,
            tanggal: "Minggu, 3 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "13:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 3,
            tanggal: "Minggu, 3 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "13:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 3,
            tanggal: "Minggu, 3 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "13:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 3,
            tanggal: "Minggu, 3 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "13:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 3,
            tanggal: "Minggu, 3 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "13:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 3,
            tanggal: "Minggu, 3 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:30",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 3,
            tanggal: "Minggu, 3 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:30",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 3,
            tanggal: "Minggu, 3 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:30",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 3,
            tanggal: "Minggu, 3 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:30",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        [
            {
                day: 1,
                tanggal: "Jumat, 1 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "19:00",
                tim1: "Himpunan Mahasiswa Fisika Teknik",
                image1: "/HMFT_ITB.png",
                skor1: 0,
                tim2: "Himpunan Mahasiswa Teknik Lingkungan",
                image2: "/HMTL_ITB.jpg",
                skor2: 0
            },
            {
                day: 1,
                tanggal: "Jumat, 1 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "19:00",
                tim1: "Himpunan Mahasiswa Mesin",
                image1: "/HMM_ITB.png",
                skor1: 0,
                tim2: "Mahasiswa Teknik Industri (A)",
                image2: "/MTI_ITB.png",
                skor2: 0
            },
            {
                day: 1,
                tanggal: "Jumat, 1 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "19:00",
                tim1: "Himpunan Mahasiswa Elektro",
                image1: "/HME_ITB.png",
                skor1: 0,
                tim2: "Ikatan Mahasiswa Kewirausahaan \"Artha\"",
                image2: "/IMK_ARTHA_ITB.jfif",
                skor2: 0
            },
            {
                day: 1,
                tanggal: "Jumat, 1 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "19:00",
                tim1: "Himpunan Mahasiswa Teknik Perminyakan \"Patra\"",
                image1: "/HMTM_PATRA_ITB.png",
                skor1: 0,
                tim2: "Ikatan Mahasiswa Metalurgi",
                image2: "/IMMG_ITB.png",
                skor2: 0
            },
            {
                day: 1,
                tanggal: "Jumat, 1 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "19:00",
                tim1: "Himpunan Mahasiswa Sipil (A)",
                image1: "/HMS_ITB.png",
                skor1: 0,
                tim2: "Keluarga Mahasiswa Teknik Penerbangan (A)",
                image2: "/KMPN_ITB.png",
                skor2: 0
            },
            {
                day: 1,
                tanggal: "Jumat, 1 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "19:00",
                tim1: "Himpunan Mahasiswa Astronomi",
                image1: "/Himastron_ITB.jfif",
                skor1: 0,
                tim2: "Mahasiswa Teknik Industri (B)",
                image2: "/MTI_ITB.png",
                skor2: 0
            },
            {
                day: 1,
                tanggal: "Jumat, 1 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "19:00",
                tim1: "Himpunan Mahasiswa Tambang (B)",
                image1: "/HMT_ITB.jpg",
                skor1: 0,
                tim2: "Keluarga Mahasiswa Manajemen (B)",
                image2: "/KMM_ITB.png",
                skor2: 0
            },
            {
                day: 1,
                tanggal: "Jumat, 1 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "19:00",
                tim1: "Himpunan Mahasiswa Matematika (B)",
                image1: "/HIMATIKA_ITB.png",
                skor1: 0,
                tim2: "Ikatan Mahasiswa Geodesi",
                image2: "/IMG_ITB.jpg",
                skor2: 0
            },
            {
                day: 1,
                tanggal: "Jumat, 1 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "19:00",
                tim1: "Himpunan Mahasiswa Teknik Material",
                image1: "/MTM_ITB.png",
                skor1: 0,
                tim2: "Himpunan Mahasiswa Biologi \"Nymphaea\"",
                image2: "/HIMABIO_Nymphaea_ITB.jfif",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Farmasi 'Ars Praeparandi'",
                image1: "/HMF_Ars_Praeparandi_ITB.png",
                skor1: 0,
                tim2: "TBD",
                image2: "/TBD.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Meteorologi 'Atmosphaira' (B)",
                image1: "/HMME_Atmosphaira_ITB.png",
                skor1: 0,
                tim2: "Himpunan Mahasiswa Informatika",
                image2: "/HMIF_ITB.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Sipil (B)",
                image1: "/HMS_ITB.png",
                skor1: 0,
                tim2: "TBD",
                image2: "/TBD.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Teknik Geofisika 'Terra'",
                image1: "/HIMA_TG_TERRA_ITB.jpg",
                skor1: 0,
                tim2: "TBD",
                image2: "/TBD.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Teknik Perencanaan Wilayah dan Kota 'Pangripta Loka' (B)",
                image1: "/HMP_PL_ITB.png",
                skor1: 0,
                tim2: "TBD",
                image2: "/TBD.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Fisika",
                image1: "/HIMAFI_ITB.jpg",
                skor1: 0,
                tim2: "Keluarga Mahasiswa Teknik Kelautan",
                image2: "/KMKL_ITB.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Teknik Perencanaan Wilayah dan Kota 'Pangripta Loka' (A)",
                image1: "/HMP_PL_ITB.png",
                skor1: 0,
                tim2: "TBD",
                image2: "/TBD.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Fisika Teknik (A)",
                image1: "/HMFT_ITB.png",
                skor1: 0,
                tim2: "Himpunan Mahasiswa Tambang (A)",
                image2: "/HMT_ITB.jpg",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Teknik Bioenergi dan Kemurgi 'RINUVA'",
                image1: "/HMTB_RINUVA_ITB.png",
                skor1: 0,
                tim2: "TBD",
                image2: "/TBD.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Elektroteknik",
                image1: "/HME_ITB.png",
                skor1: 0,
                tim2: "Keluarga Mahasiswa Seni Rupa (A)",
                image2: "/KMSR_ITB.jfif",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Matematika (A)",
                image1: "/HIMATIKA_ITB.png",
                skor1: 0,
                tim2: "TBD",
                image2: "/TBD.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Ikatan Mahasiswa Arsitektur-Gunadharma",
                image1: "/IMA_G_ITB.jpg",
                skor1: 0,
                tim2: "TBD",
                image2: "/TBD.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Oseanografi 'Triton'",
                image1: "/HMO_TRITON_ITB.png",
                skor1: 0,
                tim2: "TBD",
                image2: "/TBD.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Ikatan Mahasiswa Telekomunikasi 'Signum'",
                image1: "/IMT_Signum_ITB.jpg",
                skor1: 0,
                tim2: "Himpunan Mahasiswa Teknik Kimia",
                image2: "/HIMATEK_ITB.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Mesin (A)",
                image1: "/HMM_ITB.png",
                skor1: 0,
                tim2: "TBD",
                image2: "/TBD.png",
                skor2: 0
            },
            {
                day: 2,
                tanggal: "Sabtu, 2 November 2024",
                lokasi: "Online",
                sportName: "Valorant",
                waktu: "13:00",
                tim1: "Himpunan Mahasiswa Meteorologi 'Atmosphaira' (A)",
                image1: "/HMME_Atmosphaira_ITB.png",
                skor1: 0,
                tim2: "Keluarga Mahasiswa Seni Rupa (B)",
                image2: "/KMSR_ITB.jfif",
                skor2: 0
            }
        ]
    ],
    },
    {
        week  : 2,
        match :
        [{
            day: 4,
            tanggal: "Minggu, 10 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "13:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 4,
            tanggal: "Minggu, 10 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "13:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        },
        {
            day: 4,
            tanggal: "Minggu, 10 November 2024",
            lokasi: "Online",
            sportName: "Mobile Legends: Bang Bang",
            waktu: "15:00",
            tim1: "TBD",
            image1 : "/TBD.png",
            skor1: "0",
            tim2: "TBD",
            image2 : "/TBD.png",
            skor2: "0",
        }]
    }
]