export const schedule = [
    {
        week: 1,
        match : [
            {
                day:3,
                tanggal:"Rabu, 16 Agustus 2024",
                lokasi:"Gor 2 Futsal ITB Jatinangor",
                sportName: "Futsal",
                waktu: "14:00",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "HMIF.svg",
                skor2: "1",
            },
            {
                day:3,
                tanggal:"Rabu, 16 Agustus 2024",
                lokasi:"Gor 2 Futsal ITB Jatinangor",
                sportName: "Futsal",
                waktu: "14:00",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "HMIF.svg",
                skor2: "1",
            },
            {
                day:3,
                tanggal:"Rabu, 16 Agustus 2024",
                lokasi:"Gor 2 Futsal ITB Jatinangor",
                sportName: "Futsal",
                waktu: "14:00",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "HMIF.svg",
                skor2: "1",
            },
            {
                day:3,
                tanggal:"Rabu, 16 Agustus 2024",
                lokasi:"Gor 2 Futsal ITB Jatinangor",
                sportName: "Futsal",
                waktu: "14:00",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "HMIF.svg",
                skor2: "1",
            },
            {
                day:4,
                tanggal:"Kamis, 17 Agustus 2024",
                lokasi:"Gor 2 Futsal ITB Jatinangor",
                sportName: "Futsal",
                waktu: "14:00",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "HMIF.svg",
                skor2: "1",
            },
            {
                day:4,
                tanggal:"Kamis, 17 Agustus 2024",
                lokasi:"Gor 2 Futsal ITB Jatinangor",
                sportName: "Futsal",
                waktu: "14:00",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "HMIF.svg",
                skor2: "1",
            },
        ],
    },
    {
        week: 2,
        match : [
            {
                day:3,
                tanggal:"Rabu, 16 Agustus 2024",
                lokasi:"Gor 2 Futsal ITB Jatinangor",
                sportName: "Futsal",
                waktu: "14:00",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "HMIF.svg",
                skor2: "1",
            },
        ],
    },
]