export const schedule = [
    {
        round : 1,
        match : [
            {
                sportName: "Renang Putra",
                tim1: "Keluarga Mahasiswa Penerbangan (A)",
                image1: "/KMPN.jpg",
                skor1: "0",
                tim2: "Keluarga Mahasiswa Teknik Industri",
                image2: "/MTI.jpg",
                skor2: "0",
                tim3: "Himpunan Mahasiswa Teknik Perencanaan Wilayah dan Kota (A)",
                image3: "/HMP.jpg",
                skor3: "0",
                tim4: "Ikatan Mahasiswa Telekomunikasi 'Signum' (A)",
                image4: "/IMT.jpg",
                skor4: "0",
                tim5: "Himpunan Mahasiswa Teknik Lingkungan",
                image5: "/HMTL.jpg",
                skor5: "0"
            },
            {
                sportName: "Renang Putra",
                tim1: "Himpunan Mahasiswa Oseanografi 'Triton' (A)",
                image1: "/HMO.jpg",
                skor1: "0",
                tim2: "Himpunan Mahasiswa Mesin",
                image2: "/HMM.jpg",
                skor2: "0",
                tim3: "Himpunan Mahasiswa Teknik Geologi 'GEA'",
                image3: "/HMTG.jpg",
                skor3: "0",
                tim4: "Himpunan Mahasiswa Tambang (B)",
                image4: "/HMT.jpg",
                skor4: "0",
                tim5: "Himpunan Mahasiswa Teknik Geofisika 'Terra'",
                image5: "/HIMA_TG.jpg",
                skor5: "0"
            },
            {
                sportName: "Renang Putra",
                tim1: "Himpunan Mahasiswa Biologi 'Nymphaea' (A)",
                image1: "/HIMABIO.jpg",
                skor1: "0",
                tim2: "Himpunan Mahasiswa Matematika (A)",
                image2: "/HIMATIKA.jpg",
                skor2: "0",
                tim3: "Himpunan Mahasiswa Sipil",
                image3: "/HMS.jpg",
                skor3: "0",
                tim4: "Himpunan Mahasiswa Matematika (B)",
                image4: "/HIMATIKA.jpg",
                skor4: "0",
                tim5: "Himpunan Mahasiswa Elektro (B)",
                image5: "/HME.jpg",
                skor5: "0"
            },
            {
                sportName: "Renang Putra",
                tim1: "Himpunan Mahasiswa Elektro (A)",
                image1: "/HME.jpg",
                skor1: "0",
                tim2: "Ikatan Mahasiswa Kewirausahaan 'Artha' (B)",
                image2: "/IMK.jpg",
                skor2: "0",
                tim3: "Ikatan Mahasiswa Metalurgi (A)",
                image3: "/IMMG.jpg",
                skor3: "0",
                tim4: "Himpunan Mahasiswa Teknik Perencanaan Wilayah dan Kota (B)",
                image4: "/HMP.jpg",
                skor4: "0",
                tim5: "Keluarga Mahasiswa Seni Rupa",
                image5: "/KMSR.jpg",
                skor5: "0"
            },
            {
                sportName: "Renang Putra",
                tim1: "Himpunan Mahasiswa Informatika (A)",
                image1: "/HMIF.jpg",
                skor1: "0",
                tim2: "Ikatan Mahasiswa Kewirausahaan 'Artha' (A)",
                image2: "/IMK.jpg",
                skor2: "0",
                tim3: "Himpunan Mahasiswa Teknik Material",
                image3: "/MTM.jpg",
                skor3: "0",
                tim4: "Ikatan Mahasiswa Metalurgi (B)",
                image4: "/IMMG.jpg",
                skor4: "0",
                tim5: "Keluarga Mahasiswa Teknik Kelautan (B)",
                image5: "/KMKL.jpg",
                skor5: "0"
            },
            {
                sportName: "Renang Putra",
                tim1: "Himpunan Mahasiswa Biologi 'Nymphaea' (B)",
                image1: "/HIMABIO.jpg",
                skor1: "0",
                tim2: "Keluarga Mahasiswa Teknik Kelautan (A)",
                image2: "/KMKL.jpg",
                skor2: "0",
                tim3: "Himpunan Mahasiswa Oseanografi 'Triton' (B)",
                image3: "/HMO.jpg",
                skor3: "0",
                tim4: "Keluarga Mahasiswa Penerbangan (B)",
                image4: "/KMPN.jpg",
                skor4: "0",
                tim5: "Himpunan Mahasiswa Informatika (B)",
                image5: "/HMIF.jpg",
                skor5: "0"
            },
            {
                sportName: "Renang Putra",
                tim1: "Ikatan Mahasiswa Telekomunikasi 'Signum' (B)",
                image1: "/IMT.jpg",
                skor1: "0",
                tim2: "Himpunan Mahasiswa Tambang (A)",
                image2: "/HMT.jpg",
                skor2: "0",
                tim3: "Himpunan Mahasiswa Fisika Teknik",
                image3: "/HMFT.jpg",
                skor3: "0",
                tim4: "-",
                image4: "/NONE.jpg",
                skor4: "-",
                tim5: "-",
                image5: "/NONE.jpg",
                skor5: "-"
            }]
    },
]