export const schedule = [
    {
        round : 1,
        match : [
            {
                sportName: "Renang Putri",
                tim1: "Himpunan Mahasiswa Tambang (A)",
                image1: "/HMT.jpg",
                skor1: "0",
                tim2: "Keluarga Mahasiswa Seni Rupa (A)",
                image2: "/KMSR.jpg",
                skor2: "0",
                tim3: "Himpunan Mahasiswa Informatika",
                image3: "/HMIF.jpg",
                skor3: "0",
                tim4: "Ikatan Mahasiswa Metalurgi (A)",
                image4: "/IMMG.jpg",
                skor4: "0",
                tim5: "Himpunan Mahasiswa Tambang (B)",
                image5: "/HMT.jpg",
                skor5: "0"
            },
            {
                sportName: "Renang Putri",
                tim1: "Keluarga Mahasiswa Penerbangan (A)",
                image1: "/KMPN.jpg",
                skor1: "0",
                tim2: "Himpunan Mahasiswa Teknik Perencanaan Wilayah dan Kota",
                image2: "/HMP.jpg",
                skor2: "0",
                tim3: "Himpunan Mahasiswa Oseanografi 'Triton' (A)",
                image3: "/HMO.jpg",
                skor3: "0",
                tim4: "Ikatan Mahasiswa Telekomunikasi 'Signum' (A)",
                image4: "/IMT.jpg",
                skor4: "0",
                tim5: "Himpunan Mahasiswa Mesin",
                image5: "/HMM.jpg",
                skor5: "0"
            },
            {
                sportName: "Renang Putri",
                tim1: "Himpunan Mahasiswa Teknik Geofisika 'Terra'",
                image1: "/HIMA_TG.jpg",
                skor1: "0",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "/HME.jpg",
                skor2: "0",
                tim3: "Keluarga Mahasiswa Seni Rupa (B)",
                image3: "/KMSR.jpg",
                skor3: "0",
                tim4: "Himpunan Mahasiswa Teknik Material",
                image4: "/MTM.jpg",
                skor4: "0",
                tim5: "Himpunan Mahasiswa Biologi 'Nymphaea' (A)",
                image5: "/HIMABIO.jpg",
                skor5: "0"
            },
            {
                sportName: "Renang Putri",
                tim1: "Keluarga Mahasiswa Teknik Industri",
                image1: "/MTI.jpg",
                skor1: "0",
                tim2: "Ikatan Mahasiswa Telekomunikasi 'Signum' (B)",
                image2: "/IMT.jpg",
                skor2: "0",
                tim3: "Ikatan Mahasiswa Metalurgi (B)",
                image3: "/IMMG.jpg",
                skor3: "0",
                tim4: "Himpunan Mahasiswa Teknik Lingkungan",
                image4: "/HMTL.jpg",
                skor4: "0",
                tim5: "Keluarga Mahasiswa Penerbangan (B)",
                image5: "/KMPN.jpg",
                skor5: "0"
            },
            {
                sportName: "Renang Putri",
                tim1: "Himpunan Mahasiswa Sipil",
                image1: "/HMS.jpg",
                skor1: "0",
                tim2: "Himpunan Mahasiswa Biologi 'Nymphaea' (B)",
                image2: "/HIMABIO.jpg",
                skor2: "0",
                tim3: "Himpunan Mahasiswa Oseanografi 'Triton' (B)",
                image3: "/HMO.jpg",
                skor3: "0",
                tim4: "-",
                image4: "/NONE.jpg",
                skor4: "-",
                tim5: "-",
                image5: "/NONE.jpg",
                skor5: "-"
            }]
    },
]