export const schedule = [
    {
        round: 1,
        match : [
            {
                sportName: "Futsal",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "/HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "/HMIF.svg",
                skor2: "1",
            },
            {
                sportName: "Futsal",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "/HMIF.svg",
                skor1: "3",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "/HMIF.svg",
                skor2: "1",
            },
            {
                sportName: "Futsal",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "/HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "/HMIF.svg",
                skor2: "1",
            },
            {
                sportName: "Futsal",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "/HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "/HMIF.svg",
                skor2: "1",
            },
            {
                sportName: "Futsal",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "/HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "/HMIF.svg",
                skor2: "1",
            },
            {
                sportName: "Futsal",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "/HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "/HMIF.svg",
                skor2: "1",
            },
        ],
    },
    {
        round: 2,
        match : [
            {
                sportName: "Futsal",
                tim1: "Himpunan Mahasiswa Informatika",
                image1: "/HMIF.svg",
                skor1: "4",
                tim2: "Himpunan Mahasiswa Elektroteknik",
                image2: "/HMIF.svg",
                skor2: "1",
            },
        ],
    },
  ]